server:
  port: 8764

jwt:
  secret: 7A24432646294A404E635266556A576E5A7234753778214125442A472D4B6150645367566B59703273357638792F423F4528482B4D6251655468576D5A713474

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_core_alims
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: core-alims-service
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411/