# A gateway service is a component in a microservices architecture that acts as a front door
# for all incoming requests. Its main function is to handle incoming requests from clients,
# route them to the appropriate microservice, and then return the response back to the client.

server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    root: INFO
    org.springframework.cloud.gatewayroute.RouteDefinitionLocatior: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        ## -
        ## --
        ## ---
        ## Route to alims service
        - id: core-alims-service
          uri: lb://core-alims-service
          predicates:
            - Path=/airline/**

        ## Route to assets of alims service(admin login assets)
        - id: alims-login-assets
          uri: lb://core-alims-service
          predicates:
            - Path=/systemAdminLoginDashboard/**

        ## Route to assets of alims service(admin dashboard assets)
        - id: alims-dashboard-assets
          uri: lb://core-alims-service
          predicates:
            - Path=/systemAdminDashboard/**

        ## -
        ## --
        ## ---
        ## Route to admin service
        - id: core-alims-admin-service
          uri: lb://core-alims-admin-service
          predicates:
            - Path=/admin/**

        ## Route to assets of admin service
        - id: admin-assets
          uri: lb://core-alims-admin-service
          predicates:
            - Path=/**





